export const ADMIN_ALL_USERS_REQUEST = "ADMIN_ALL_USERS_REQUEST";
export const ADMIN_ALL_USERS_SUCCESS = "ADMIN_ALL_USERS_SUCCESS";
export const ADMIN_ALL_USERS_FAILURE = "ADMIN_ALL_USERS_FAILURE";

export const ADMIN_SINGLE_USER_REQUEST = "ADMIN_SINGLE_USER_REQUEST";
export const ADMIN_SINGLE_USER_SUCCESS = "ADMIN_SINGLE_USER_SUCCESS";
export const ADMIN_SINGLE_USER_FAILURE = "ADMIN_SINGLE_USER_FAILURE";

export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_FAILURE = "ADMIN_UPDATE_USER_FAILURE";

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_FAILURE = "ADMIN_DELETE_USER_FAILURE";

export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST";
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS";
export const ADMIN_ADD_PRODUCT_FAILURE = "ADMIN_ADD_PRODUCT_FAILURE";
export const ADMIN_ADD_PRODUCT_INIT = "ADMIN_ADD_PRODUCT_INIT";

export const ADMIN_ALL_ORDERS_REQUEST = "ADMIN_ALL_ORDERS_REQUEST";
export const ADMIN_ALL_ORDERS_SUCCESS = "ADMIN_ALL_ORDERS_SUCCESS";
export const ADMIN_ALL_ORDERS_FAILURE = "ADMIN_ALL_ORDERS_FAILURE";


export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_FAILURE = "ADMIN_DELETE_PRODUCT_FAILURE";