let i = 1;
const products = [
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `iPhone ${++i}`,
    image: `${++i}`,
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
];

export default products;
