let i = 1;
const products = [
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: false,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
  {
    _id: `ID: ${++i}`,
    user: `${++i}`,
    name: `Netflix ${++i}`,
    image: "/uploads/netflix.jpg",
    price: `${++i}`,
    isAvailable: `${++i}`,
  },
];

export default products;
